---
title: "BAN430"
output: pdf_document
date: "2023-01-27"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tsibble)
library(fpp3)
library(readxl)
library(lubridate)

```

```{r}
theme_set(theme_bw())
```

```{r}
df = read_excel("US10YTRR.xlsx",sheet = "Mid")

names(df) <- toupper(names(df))

tdf = df%>%
  mutate(DATE = date(DATE))%>%
  mutate(YEAR = year(DATE))%>%
  filter(between(YEAR,2010,2021))%>%
  select(-YEAR)%>%
  mutate(YEARMONTH = tsibble::yearmonth(DATE))%>%
  group_by(YEARMONTH)%>%
  summarize(MEANPRICE = mean(PRICE,na.rm = T))
  

tdf%>%
  ggplot(aes(x=YEARMONTH,y=MEANPRICE))+
  geom_line(col="blue")+
  geom_point(col="green",size=3)+
  theme_bw()+
  scale_x_yearmonth(breaks=seq(yearmonth("2010 Jan"),yearmonth("2022 Jan"),by=12),
                    labels=2010:2022)+
  theme(panel.grid.minor = element_blank())+
  labs(y = "Monthly 10Y US bond index",
       x = "Time (month)")


```


```{r}

df_tsb1 = df%>%
  mutate(DATE = date(DATE))%>%
  as_tsibble(index=DATE)

df_tsb1%>%
  autoplot(.vars = PRICE, color="magenta")

```


```{r}

df_tsb1%>%
  index_by(YEARMONTH = ~yearmonth(.))%>%
  summarize(MEANPRICE = mean(PRICE, na.rm = T))%>%
  autoplot(MEANPRICE)

df_tsb1%>%
  index_by(YEARWEEK = ~yearweek(.))%>%
  summarize(MEANPRICE = mean(PRICE, na.rm = T))%>%
  autoplot(MEANPRICE)

df_tsb1%>%
  index_by(YEAR = ~year(.))%>%
  summarize(MEANPRICE = mean(PRICE, na.rm = T))%>%
  autoplot(MEANPRICE)

```

```{r}

#install.packages("nycflights13", lib = .libPaths()[2])

weather <- nycflights13::weather%>%
  select(origin,time_hour,temp,humid,precip)

weather_tsb1 = as_tsibble(weather, key = origin,index = time_hour)

full_weather = weather_tsb1%>%
  fill_gaps(precip = 0)%>%
  group_by_key()%>%
  tidyr::fill(temp,humid, .direction = "down")

full_weather%>%
  group_by_key()%>%
  index_by(year_month = ~yearmonth(.))%>%
  summarize(avg_temp = mean(temp,na.rm = T),
            ttl_precip = sum(precip,na.rm = T))%>%
  autoplot(ttl_precip)
  
```

```{r}
windpower = OffshoreWindtwoLocationsFiveYears
rm(OffshoreWindtwoLocationsFiveYears)

wind_tsb1 = windpower%>%
  as_tsibble(key=Place, index = datetime)

wind_tsb1%>%
  autoplot(powerprod)

wind_tsb1%>%
  group_by_key()%>%
  index_by(date = ~as.Date(.))%>%
  summarise(Power = mean(powerprod,na.rm = T))%>%
  autoplot(Power)
  
```

```{r}
wind_tsb1%>%
  group_by_key()%>%
  index_by(Yearmonth = ~yearmonth(.))%>%
  summarise(Power = mean(powerprod,na.rm = T))%>%
  autoplot(Power)
```


```{r}
pivot
```

